server:
  port: 31000
spring:
  application:
    name: xc‐service‐manage‐cms‐client
  data:
    mongodb:
      uri:  mongodb://root:example@11.0.0.184:27017
      database: xc_cms
  freemarker:
    cache: false
    setting:
      template_update_delay: 0