server:
  port: 31000
spring:
  application:
    name: xc‐service‐manage‐cms‐client
  data:
    mongodb:
      uri:  mongodb://root:example@39.104.50.29:7010
      database: xc_cms
  rabbitmq:
    host: 39.104.50.29
    port: 7007
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1